version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    command: redis-server
    ports:
        - "6379:6379"
  server:
    build: server/
    restart: always
    depends_on:
      - redis
    ports:
      - "5000:5000"
  client:
    build: client/
    restart: always
    network_mode: host
    depends_on:
      - server
    ports:
      - "80:80"
